version: "3"
services:
  web-content:
    build: ./web-content
    image: alexsimons/web-content
    ports:
      - "3000:3000"
    volumes:
      - ./web-content:/app
    entrypoint:
      - npm
      - run
      - watch
  web-service:
    build: ./web-service
    image: alexsimons/web-service
